.github/PULL_REQUEST_TEMPLATE.md
[AN-85](https://agh-student.atlassian.net/browse/AN-85)
A pull request template to make descriptions consistent.
The template should load automatically when creating a new pull request.
=> Pull request template added

.github/workflows/main.yml, frontend/sumo-championship/.eslintrc.json, frontend/sumo-championship/.prettierrc, frontend/sumo-championship/README.md, frontend/sumo-championship/package.json, frontend/sumo-championship/src/App.tsx, frontend/sumo-championship/src/index.tsx, frontend/sumo-championship/tsconfig.json, frontend/sumo-championship/yarn.lock
[AN-99](https://agh-student.atlassian.net/browse/AN-99)
Configure ESlint and Prettier + GitHub actions
=> [AN-99] Configure ESlint and Prettier

backend/sumo-championship/pom.xml, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/WrestlerController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/WrestlersDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/WrestlersResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/ClubRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/WebsiteUserRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/WrestlerRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerService.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/WrestlerRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/WrestlerServiceTest.java
JIRA_LINK
Implementation of service, repository and controller of Wrestler model. It allows to get information about Wrestlers belongs to specific users.  Endpoint implement pagination with static size. 
Tested repository and service
=> Implementation of endpoint for getting all Sumo Wrestlers

backend/sumo-championship/pom.xml, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/SeasonController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/WrestlerController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/CategoryDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/request/SeasonRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/WrestlersResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Category.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Season.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/CategoryRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/SeasonRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/WrestlerRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/SeasonService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerService.java, backend/sumo-championship/src/main/resources/application.properties, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/WrestlerServiceTest.java
JIRA_LINK
[AN-27](https://agh-student.atlassian.net/browse/AN-27)
Implemented Endpoint for creating new season (POST method). Each season contains few categories. Data validation such as (comparing ages, comparing weights etc.) are provided. Also, swagger UI dependency is added to provide readable interface for frontend-team. Instruction are included in Read.me file.  
Tested some cases (adding wrong and correct season's) to database via Postman. It will be tested more precisely at the end of User Story
=> [AN-27] Adding Seasons with Categories

.github/workflows/main.yml, .github/workflows/maven.yml
JIRA LINK: None
fixed CI that checks branch main to the one that checks dev branch
everything should work for new PRs
=> CI for dev branch instead of main

frontend/sumo-championship/.eslintrc.json, frontend/sumo-championship/package.json, frontend/sumo-championship/yarn.lock
Fix frontend eslint bug that caused whole app to fail
JIRA_LINK
---
1. Run `yarn start`
2. Verify if editing and saving files doesn't return app build error
=> Fix frontend app build errors

backend/sumo-championship/README.md, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/CategoryController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/SeasonController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/CategoryDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/SeasonDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/AllSeasonResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/CategoriesResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Season.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/CategoryRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/SeasonRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/CategoryService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/SeasonService.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/CategoryRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/SeasonRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/SeasonServiceTest.java
JIRA_LINK
Add endpoints for: <br>
* getting all seasons (name + start date + end date)
* getting seasons details (name + start date + end date), but only for one specified Season (by Season name)
* getting categories assigned to a season (by Season name)
Also add READ.ME how to use Swagger. This is instructions for frontend-team. 
Additionally, changed season name to be unique. 
Test endpoints in Postman. Also provided test for repositories and services for Season and Category models.
=> [AN-28] Get Endpoints for Categories and Seasons

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/CategoryController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/SeasonController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/WrestlerController.java
JIRA_LINK
Add @CROSSORIGIN in every existing controller
=> [AN-24] Fix Cors

backend/sumo-championship/src/main/resources/application.properties, frontend/sumo-championship/src/api/season.ts, frontend/sumo-championship/src/components/molecules/SelectField.tsx, frontend/sumo-championship/src/components/organisms/AddTournamentForms/GeneralTrounamentInformation.tsx, frontend/sumo-championship/src/pages/AddTournament.tsx, frontend/sumo-championship/src/styles/Molecules.css, frontend/sumo-championship/src/styles/Organisms.css, frontend/sumo-championship/src/types/Tournaments.ts
JIRA_LINK
[AN-32](https://agh-student.atlassian.net/browse/AN-32)
=> feature/AN-32 - Component for general tournament information ready

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/AuthController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/LoginDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/WebsiteUserResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/config/SecurityConfig.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/WebsiteUserRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/CustomUserDetailsService.java, backend/sumo-championship/src/main/resources/application.properties, frontend/sumo-championship/src/api/generalUtils.ts, frontend/sumo-championship/src/api/login.ts, frontend/sumo-championship/src/contexts/UserContext.tsx
[AN-21](https://agh-student.atlassian.net/browse/AN-21)
Implementation contains only basic login system. Securing API requests was moved to [AN-104](https://agh-student.atlassian.net/browse/AN-104) (as discussed - it's important but not required for working demo).
Sending a POST request (eg. from Postman):
```
localhost:8080/api/v1/auth/login
```
```json
{
"email": "<email>",
"password": "<password>"
}
```
should return user details. In case of invalid credentials answer is 403.
=> [AN-21] Feature: Website User Login

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/CategoryController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/TournamentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/CategoryDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/LocationDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/TournamentDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/request/CategoryRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/request/SeasonRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/request/TournamentRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/AllTournamentsResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Location.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/CategoryRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/LocationRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/SeasonRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/TournamentRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/CategoryService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/SeasonService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/TournamentService.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/LocationRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/SeasonRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/repository/TournamentRepositoryTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/SeasonServiceTest.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/TournamentServiceTest.java, frontend/sumo-championship/src/styles/Molecules.css
JIRA_LINK
[AN-33](https://agh-student.atlassian.net/browse/AN-33) 
[AN-110](https://agh-student.atlassian.net/browse/AN-33)
Implementation of POST Tournament. All details are available on Swagger
=> [AN-33][AN-110]

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/SeasonController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/TournamentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/LocationDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/TournamentDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/request/TournamentRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/response/SeasonDetailsResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Tournament.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/TournamentRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/SeasonService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/TournamentService.java, backend/sumo-championship/src/test/java/com/sumoc/sumochampionship/service/TournamentServiceTest.java
JIRA_LINK
[AN-111][(https://agh-student.atlassian.net/browse/AN-111)](https://agh-student.atlassian.net/browse/AN-111) 
Add endpoints described in the link above
=> [AN-111] Add remaining endpoints

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/tournament/TournamentDto.java
JIRA_LINK
[AN-132](https://agh-student.atlassian.net/browse/AN-132)
Add Tournament id to TournamentDto. It is must have to  **export wrestlers to Csv** and i forgot about it
Tested in Swagger UI and in frontend server
=> [AN-132] Quick change of TournamentDto

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/CountryController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/db/season/Country.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/ClubService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/TournamentService.java
JIRA_LINK
[AN-149](https://agh-student.atlassian.net/browse/AN-149)
Implementation of Country Enum to determine which countries our system supports.
It should be persist in database but due to the integration with existing system it is implemented in this way.
Tested in Swagger UI
=> [AN-149] Add Country Enum

frontend/sumo-championship/src/components/organisms/Nav.tsx, frontend/sumo-championship/src/styles/Nav.css
JIRA_LINK
[AN-140](https://agh-student.atlassian.net/browse/AN-140)
=> AN-140: fix

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/TournamentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v2/SeasonController2.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/season/SeasonDetailsResponse2.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/tournament/TournamentDetailsResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/SeasonService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/TournamentService.java
JIRA_LINK
[AN-151](https://agh-student.atlassian.net/browse/AN-151)
Implementation of endpoints that returning season and tournament details with category logic discussed with client.
Tested in Swagger UI
=> [AN-151] Season and Tournament Details

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/WebsiteUserController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/websiteuser/WebsiteUserRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WebsiteUserService.java
[AN-119](https://agh-student.atlassian.net/browse/AN-119)
Endpoint for adding users
Swagger UI
=> [AN-119] Endpoint for adding users

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/ClubController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/repository/ClubRepository.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/ClubService.java
[AN-158](https://agh-student.atlassian.net/browse/AN-158)
Endpoint for getting all clubs from country.
```sh
curl -X 'GET' 'http://localhost:8080/api/v1/club/from-country?countryName=Poland' -H 'accept: */*'
```
```sh
curl -X 'GET' 'http://localhost:8080/api/v1/club/from-country?countryName=invalid' -H 'accept: */*'
```
=> [AN-158] Endpoint for getting clubs from given country

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/WrestlerEnrollmentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/category/CategoryDto2.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/category/helpers/WeightDetailsRequest.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestlerenrollment/WrestlerEnrollmentDto2.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestlerenrollment/WrestlerEnrollmentResponse.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerEnrollmentService.java
JIRA_LINK
Endpoints for getting wrestlers that are enrolled to Tournament. Authorisation must be implemented to make this works correctly.
Only in Swagger
=> [AN-152] Endpoints for getting wrestlers to Tournament

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/WrestlerEnrollmentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestlerenrollment/WrestlerEnrollmentDto2.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerEnrollmentService.java
JIRA_LINK
[AN-161](https://agh-student.atlassian.net/browse/AN-161)
Implementation of endpoint for getting all wrestlers enrolled for certain Tournament
=> [AN-161] All Wrestlers enrolled for certain Tournament

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/WrestlerController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestler/WrestlersDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestler/WrestlersResponseNoPag.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerEnrollmentService.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerService.java
JIRA_LINK
[AN-163](https://agh-student.atlassian.net/browse/AN-163)
Implementing endpoint fot getting all Wrestlers that belong to Club.
Add Club name to Wrestlers Dto
Tested via Swagger UI
=> [AN-163] Get all club wrestlers

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/dto/wrestler/WrestlersDto.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/service/WrestlerService.java
[AN-164](https://agh-student.atlassian.net/browse/AN-164)
=> [AN-164] Bug

backend/sumo-championship/src/main/resources/application.properties, frontend/sumo-championship/src/components/organisms/Nav.tsx, frontend/sumo-championship/src/contexts/UserContext.tsx
JIRA_LINK
[AN-165](https://agh-student.atlassian.net/browse/AN-165
=> AN-165: logout added

backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/TournamentController.java, backend/sumo-championship/src/main/java/com/sumoc/sumochampionship/api/controller/v1/WebsiteUserController.java, frontend/sumo-championship/src/api/trainer.ts, frontend/sumo-championship/src/components/organisms/AddTrainerForm/AddTrainerForm.tsx
JIRA_LINK
[AN-166](https://agh-student.atlassian.net/browse/AN-166)
Repair adding Website Users
Test in web app, swagger and Postman
=> [AN-166] Fix adding website User

frontend/sumo-championship/package.json, frontend/sumo-championship/src/api/api.ts, frontend/sumo-championship/src/pages/TournamentPage.tsx, frontend/sumo-championship/yarn.lock
[AN-116](https://agh-student.atlassian.net/browse/AN-116)
=> Add export button
